### ISSUE TITLE
Provide repo for documentation

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/website-adoptium#120]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

Create a documentation repository that contains sample documentation (best would be a copy of the “migration”, “supported platforms”, and “support” pages from adoptopenjdk.net. The documentation of the wanted structure can be found here: https://docs.google.com/document/d/1AHxz5hSr4MJApAuPOYzjY7CLRTOHJgh7gxgGFUV2WAk/edit

If everything is configured correctly the rendered documentation files should already look quite in the GitHub view.

We have created the https://github.com/AdoptOpenJDK/website-adoptium-documentation repo to provide the first documentation.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Start a Pull Request.
- [x]  Done 👍 Ask in comments for a review :)
- [x]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [x]  You did it 🎉 We will merge the fix in the master branch.
- [x]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by CKeibel** [comment]
Hi,I am very interested in this task

**Comment by hendrikebbers** [comment]
Great! I will @CKeibel assign to this issue. @CKeibel you can find a step by step list in the description of the issue and you can mark any com plate step directly in the list.

**Comment by CKeibel** [comment]
thank you very much @hendrikebbers!

**Comment by hendrikebbers** [comment]
@CKeibel do you have any additional questions? It's important that the work is done in the https://github.com/AdoptOpenJDK/website-adoptium-documentation repo and not in this repo. This repo just contains all the issues for the page.

**Comment by CKeibel** [comment]
Thank you, so far I have no further questions.

**Comment by hendrikebbers** [comment]
Congrats @CKeibel for your first merged PR :)

**Comment by CKeibel** [comment]
thank you very much @hendrikebbers !  :)
