### ISSUE TITLE
Website shows previous release JREs listed in next release row,eg.jdk8u302-JRE listed under jdk8u312 row

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/website-adoptium#122]
When the latest JDK is released but the associated JRE is not yet available, the JRE download button for the previous release is listed against the new release,eg:
jdk8u312-b07 => JDK Download (jdk8u312-b07) JRE Download (jdk8u302-b08)

**Comment by karianna** [comment]
This repo is for the new website :-).  And yes we need to fix this on the existing site (there's a few issues open on this)
