### ISSUE TITLE
As a Adoptium website contributor, I want to know how to structure and label issues in GitHub/ZenHub, because we need to keep things organized.

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/website-adoptium#16]
A concrete description of the user story will be added in near future. As next steps the ZHAW students should comment on this issue to share their thoughts. Once this is done we will discuss the user story and provide a description + acceptance criteria

**Comment by timhalter** [comment]
**Persona**
![Persona_contributor.png](https://images.zenhubusercontent.com/6050bf7b64b1846719eacee9/d0380939-7b04-4562-b421-ba72b73d387a)
**Description**
As a Adoptium website contributor, I want to know how to organize structure and label issues in GitHub/ZenHub. Documentation of these organizational practices are accessible on README/GitHub Wiki.

**Acceptance criteria**

- Organizational practices and issue labeling is defined in a way that is understandable for all contributors. 

**Assignees**
fatihsolmaz22

**Comment by hendrikebbers** [comment]
@timhalter Next to the mentioned acceptance criteria it is important that all issues are labeled. Next to this you should have a look at issue templates :)

**Comment by hiddenmind3** [comment]
The documentation of how to label/structure Issues in ZenHub is in the [wiki](https://github.com/AdoptOpenJDK/website-adoptium/wiki).
The README also contains several links to this wiki article.
It contains documentation of:
- How to view the ZenHub board
- How to use the Pipelines on ZenHub in 2-week sprints
- How to create issues using templates
- How to label issues (labels, estimates, epics and sprints)
