### ISSUE TITLE
Choose Management-Tool for upcoming sprints

### ISSUE THREAD

**Issue by timhalter** [AdoptOpenJDK/website-adoptium#2]
As a team we need to find a suitable management tool.
This tool needs the following functionality:
- automatic creation of burndown charts
- automatic issue synchronizing (GitHub <-> Management Tool)

The following tools will be analyzed and discussed within the team to find the best possible solution:
- Jira
- ZenHub

**Comment by fatihsolmaz22** [comment]
As discussed (several times) we will be using Zenhub as the Issues-Management part and we will be using Confluence as the Wiki but we are most probably going to copy/paste the contents to Github later.
