### ISSUE TITLE
Define issue labeling & structure and make it accessible on GitHub

### ISSUE THREAD

**Issue by timhalter** [AdoptOpenJDK/website-adoptium#26]
To be able to understand how issues are being stucturized and labeled, a short documentation on how these points were defined should be written. The documentation must be accessible to Adoptium website contributors on GitHub.

**Comment by hiddenmind3** [comment]
The overview is on [Issue#16](https://github.com/AdoptOpenJDK/website-adoptium/issues/16) with links to the corresponding documentation
