### ISSUE TITLE
preview of PR doesnt work yet

### ISSUE THREAD

**Issue by hiddenmind3** [AdoptOpenJDK/website-adoptium#55]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel. Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior
When creating new...

## Steps to Reproduce

1.
2.
3.
4.

**Comment by julius-b** [comment]
Fixed by removing a space https://github.com/AdoptOpenJDK/website-adoptium/commit/bed263925046786a1bed559cb15412815a64b44b
