### ISSUE TITLE
Automatically redirect after clicking a download button to another site.

### ISSUE THREAD

**Issue by fatihsolmaz22** [AdoptOpenJDK/website-adoptium#58]
## Description:
Clicking on the ‘big blue button’ to download the recommended java release should redirect users to the ‘Thank You’ page while also starting the actual download.

## Acceptance criteria:
- The ‘Thank You’ page should be opened even for non-javascript users
  - if those non-js users need to click a second link, that’s okay
  - for normal (js enabled) users, the ‘Thank You’ & download start should be 1 click
- No new tabs: the ‘Thank You’ page should open in the current tab (the download should not open an additional tab, except very temporary)

**Comment by julius-b** [comment]
[22.04.2021] functionality implemented (see api_integration branch & draft pr)

**Comment by julius-b** [comment]
[01.05.2020] tested using Playwright
