### ISSUE TITLE
Looking at different template engines and deciding on which one fits best

### ISSUE THREAD

**Issue by fatihsolmaz22** [AdoptOpenJDK/website-adoptium#60]
## Description:
Template engines are Java libraries that are used to generate text output (HTML web pages) by combining templates with a data model.

## Acceptance criteria:
- Must work well with Quarkus

**Comment by hiddenmind3** [comment]
Decision Outcome:
[Qute](https://quarkus.io/guides/qute)

We have chosen Qute, because it is the only template engine that was designed to meet the Quarkus needs.

Helpful Links:
[Benefits of Qute](https://quarkus.io/blog/qute/)
[Qute Guide](https://quarkus.io/blog/qute/)
