### ISSUE TITLE
Documentation for decision of which way of creating docs is the best one

### ISSUE THREAD

**Issue by fatihsolmaz22** [AdoptOpenJDK/website-adoptium#61]

**Comment by Cr4ckii** [comment]
Decision Outcome:
[AsciiDoc](https://asciidoc.org)

AsciiDoc is often used as a documentation tool in projects, for example by quarkus and spring. So we looked at these projects and decided to use AsciiDoc as well. Furthermore the table creation in AsciiDoc is easier and offers more functionalities than others.

Helpful Links:
[spring-framework docs](https://github.com/spring-projects/spring-framework/tree/master/src/docs/asciidoc)
[quakus docs](https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc)
