### ISSUE TITLE
Create a JSON-File which contains data of working group members

### ISSUE THREAD

**Issue by timhalter** [AdoptOpenJDK/website-adoptium#77]
## Description:
This is the second step towards integrating working group members (WGM) on the website.
In order to add new sponsors we need a JSON-file which holds all the WGM data and is accessible on GitHub. A contributor can edit this JSON-file to add data of a new WGM.

## Acceptance criteria:
- A contributor is able to add the following infos of a WGM to the JSON-File on GitHub
  - Name
  - Link (Logo)
  - Link (Website)
  - Alt Text (Logo)
  - Type (enterprise, normal, …)

**Comment by thomasbuechi** [comment]
Implemented a json file with 3 example entries

One example:
>  {
    "memberName": "Microsoft",
    "memberLink": "https://microsoft.com/",
    "memberLogo": "assets/memberLogos/microsoft.svg",
    "memberAltText": "Microsoft Logo",
    "organizationType": ""
  }

**Comment by thomasbuechi** [comment]
Issue declared done as of meeting from 29.04.2021

With Shelley and Andreas
