### ISSUE TITLE
Add a "Change Language" button to Header

### ISSUE THREAD

**Issue by hiddenmind3** [AdoptOpenJDK/website-adoptium#97]
## Description:
Add a "Change Language" button to Header

## Acceptance criteria:
- The button shows all the languages that the website is avaliable in. (Dropdown menu?)
- 

## Sketches / Mockups:
See top-right of sketch
![doc2.png](https://images.zenhubusercontent.com/604e077a71af1d0f958e79e0/5d692d58-54cd-4988-a0ea-acca9fd1d2e2)

**Comment by thomasbuechi** [comment]
Implemented a Combobox in which you can change your language
